export const MAIN_PATH = '/'
export const LOGIN_PATH = '/login'
export const OPERATIONS_PATH = '/operacoes'
export const OPERATION_PATH = '/operacoes/:operationId'
export const CNPJ_SEARCH_PATH = '/pesquisar-cnpj'
