export const THEME_STORAGE_KEY = 'theme'
export const USER_STORAGE_KEY = 'user'
export const BLACK_TOKEN_STORAGE_KEY = 'black-auth-token'
export const VADU_TOKEN_STORAGE_KEY = 'vadu-auth-token'
export const MANTYZ_TOKEN_STORAGE_KEY = 'mantyz-auth-token'
